version: "3.0"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - frontend
  redis:
    image: "redis:alpine"
    networks:
      - frontend
networks:
  frontend:
    driver: bridge

